import re
from datetime import datetime
from time import gmtime, strftime

TIMESTAMP = strftime("%Y%m%d%H%M%S", gmtime())


def get_timestamp(name):
    """Gets the timestamp from a given file name

    :param name: (string) Name of a file generated by AlchemyDumps

    :return: (string) The backup numeric id (in case of success) or False
    """
    pattern = r'(.*)(-)(?P<timestamp>[\d]{14})(-)(.*)(.gz)'
    match = re.search(pattern, name)
    return match.group('timestamp') if match else False


def parse_timestamp(timestamp):
    """Transforms a timestamp ID in a humanized date"""
    date_parsed = datetime.strptime(timestamp, '%Y%m%d%H%M%S')
    return date_parsed.strftime('%b %d, %Y at %H:%M:%S')
