import re
from datetime import datetime


def get_timestamp(name):
    """从给定的文件名获取时间戳
    Gets the timestamp from a given file name

    :param name: (string) Name of a file generated by AlchemyDumps

    :return: (string) The backup numeric id (in case of success) or False
    """
    pattern = r'(.*)(-)(?P<timestamp>[\d]{14})(-)(.*)(.gz)'
    match = re.search(pattern, name)
    return match.group('timestamp') if match else False


def parse_timestamp(timestamp):
    """Transforms a timestamp ID in a humanized date

    把时间戳ID转换为可读日期
    """
    date_parsed = datetime.strptime(timestamp, '%Y%m%d%H%M%S')
    return date_parsed.strftime('%b %d, %Y at %H:%M:%S')
